<a href="https://colab.research.google.com/github/kimyieun/Data-Science/blob/master/AutoEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

num = 100000;
X = [[n, n, n] for n in range(num)];
X = torch.tensor(X).float()
X

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [2.0000e+00, 2.0000e+00, 2.0000e+00],
        ...,
        [9.9997e+04, 9.9997e+04, 9.9997e+04],
        [9.9998e+04, 9.9998e+04, 9.9998e+04],
        [9.9999e+04, 9.9999e+04, 9.9999e+04]])

In [0]:
input_size = 3
output_size = 3
hidden_size = 1io;

class Autoencoder(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Autoencoder, self).__init__()
        self.encoder = nn.Linear(input_size, hidden_size)
        self.decoder = nn.Linear(hidden_size, output_size)
        
    def forward(self, x):
        #x = F.leaky_relu(self.encoder(x))
        x = self.encoder(x)
        out = self.decoder(x)
        #out = F.leaky_relu(out)
        return out

In [44]:
autoencoder = Autoencoder(input_size, hidden_size, output_size)

loss_function = nn.MSELoss()
optimizer = torch.optim.SGD(autoencoder.parameters(), lr=0.0000001, weight_decay=1000000000)

epoch = 6
for t in range(epoch):
    optimizer.zero_grad()
    
    print(autoencoder.encoder.weight)
    output = autoencoder(X.float())
    loss = loss_function(output, X.float())

    loss.backward()
    optimizer.step()
    print(output)

    if t % 1000 == 0:
        print(output)
        print(loss.data.numpy())

Parameter containing:
tensor([[-0.1372, -0.4422, -0.4510]], requires_grad=True)
tensor([[ 3.3200e-01,  6.7145e-01, -7.1224e-01],
        [ 3.9931e-01,  1.1514e+00, -9.3024e-01],
        [ 4.6661e-01,  1.6313e+00, -1.1482e+00],
        ...,
        [ 6.7306e+03,  4.7993e+04, -2.1800e+04],
        [ 6.7307e+03,  4.7993e+04, -2.1801e+04],
        [ 6.7308e+03,  4.7994e+04, -2.1801e+04]], grad_fn=<AddmmBackward>)
tensor([[ 3.3200e-01,  6.7145e-01, -7.1224e-01],
        [ 3.9931e-01,  1.1514e+00, -9.3024e-01],
        [ 4.6661e-01,  1.6313e+00, -1.1482e+00],
        ...,
        [ 6.7306e+03,  4.7993e+04, -2.1800e+04],
        [ 6.7307e+03,  4.7993e+04, -2.1801e+04],
        [ 6.7308e+03,  4.7994e+04, -2.1801e+04]], grad_fn=<AddmmBackward>)
2915431000.0
Parameter containing:
tensor([[ 3.4821, 33.6781, 34.5447]], requires_grad=True)
tensor([[-1.4820e+03, -5.7395e+02, -2.0298e+03],
        [-1.6332e+04, -5.8059e+03, -2.3529e+04],
        [-3.1181e+04, -1.1038e+04, -4.5029e+04],
        ...,
 