In [91]:
import torch
import torch.nn as nn
import torch.nn.functional as F

num = 100000;
X = [[n, n, n] for n in range(num)];
X = torch.tensor(X).float()
X

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [2.0000e+00, 2.0000e+00, 2.0000e+00],
        ...,
        [9.9997e+04, 9.9997e+04, 9.9997e+04],
        [9.9998e+04, 9.9998e+04, 9.9998e+04],
        [9.9999e+04, 9.9999e+04, 9.9999e+04]])

In [87]:
input_size = 3
output_size = 3
hidden_size = 2

class Autoencoder(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Autoencoder, self).__init__()
        self.encoder = nn.Linear(input_size, hidden_size)
        self.latent = nn.Linear(hidden_size, 1)
        self.decoder = nn.Linear(1, output_size)
        
    def forward(self, x):
        x = F.relu(self.encoder(x))
        x = self.latent(x)
        out = self.decoder(F.relu(x))
        return out

In [ ]:
autoencoder = Autoencoder(input_size, hidden_size, output_size)

loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

epoch = 10000
for t in range(epoch):
    optimizer.zero_grad()
    output = autoencoder(X.float())
    loss = loss_function(output, X.float())
    loss.backward()
    optimizer.step()
    
    if t % 1000 == 0:
        print(output)
        print(loss.data.numpy())

tensor([[ 2.1594e-01,  9.3565e-01, -9.9603e-01],
        [ 2.9439e-01,  1.0234e+00, -8.2282e-01],
        [ 4.9649e-01,  1.2495e+00, -3.7656e-01],
        ...,
        [ 2.1001e+04,  2.3493e+04,  4.6370e+04],
        [ 2.1001e+04,  2.3494e+04,  4.6370e+04],
        [ 2.1001e+04,  2.3494e+04,  4.6371e+04]], grad_fn=<AddmmBackward>)
1663305700.0
tensor([[ 2.1594e-01,  9.3565e-01, -9.9603e-01],
        [ 2.9439e-01,  1.0234e+00, -8.2282e-01],
        [ 4.9649e-01,  1.2495e+00, -3.7656e-01],
        ...,
        [ 2.1001e+04,  2.3493e+04,  4.6370e+04],
        [ 2.1001e+04,  2.3494e+04,  4.6370e+04],
        [ 2.1001e+04,  2.3494e+04,  4.6371e+04]], grad_fn=<AddmmBackward>)
1663305700.0
